/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/counter.v:1" *)
module counter(clk, reset, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "../rtl/counter.v:7" *)
  wire [3:0] areg_next;
  (* src = "../rtl/counter.v:2" *)
  input clk;
  (* src = "../rtl/counter.v:4" *)
  output [3:0] q;
  (* src = "../rtl/counter.v:3" *)
  input reset;
  sky130_fd_sc_hd__inv_1 _06_ (
    .A(reset),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_2 _07_ (
    .A(q[0]),
    .B(q[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _08_ (
    .A(q[2]),
    .B(_04_),
    .Y(areg_next[2])
  );
  sky130_fd_sc_hd__nand3_2 _09_ (
    .A(q[0]),
    .B(q[1]),
    .C(q[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _10_ (
    .A(q[3]),
    .B(_05_),
    .Y(areg_next[3])
  );
  sky130_fd_sc_hd__inv_1 _11_ (
    .A(q[0]),
    .Y(areg_next[0])
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(q[0]),
    .B(q[1]),
    .X(areg_next[1])
  );
  sky130_fd_sc_hd__inv_1 _13_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_1 _14_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_1 _15_ (
    .A(reset),
    .Y(_02_)
  );
  (* src = "../rtl/counter.v:9" *)
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(areg_next[0]),
    .Q(q[0]),
    .RESET_B(_00_)
  );
  (* src = "../rtl/counter.v:9" *)
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(areg_next[1]),
    .Q(q[1]),
    .RESET_B(_01_)
  );
  (* src = "../rtl/counter.v:9" *)
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(areg_next[2]),
    .Q(q[2]),
    .RESET_B(_02_)
  );
  (* src = "../rtl/counter.v:9" *)
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(areg_next[3]),
    .Q(q[3]),
    .RESET_B(_03_)
  );
endmodule
