/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/sbox.v:1" *)
module sbox(in, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "../rtl/sbox.v:1" *)
  input [3:0] in;
  (* src = "../rtl/sbox.v:2" *)
  output [3:0] out;
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(in[0]),
    .B(in[3]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__inv_1 _16_ (
    .A(in[2]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(in[1]),
    .B(_00_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_14_),
    .B(_01_),
    .Y(out[0])
  );
  sky130_fd_sc_hd__nand3b_1 _19_ (
    .A_N(in[2]),
    .B(in[3]),
    .C(in[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21ai_0 _20_ (
    .A1(in[3]),
    .A2(_00_),
    .B1(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(in[3]),
    .B(in[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o22ai_1 _22_ (
    .A1(in[1]),
    .A2(in[3]),
    .B1(_04_),
    .B2(in[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(in[0]),
    .A2(_03_),
    .B1(_05_),
    .Y(out[1])
  );
  sky130_fd_sc_hd__nand3b_1 _24_ (
    .A_N(in[3]),
    .B(in[2]),
    .C(in[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _25_ (
    .A1(in[1]),
    .A2(in[2]),
    .B1(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_4 _26_ (
    .A(in[3]),
    .SLEEP(in[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__o32ai_2 _27_ (
    .A1(in[0]),
    .A2(in[2]),
    .A3(_08_),
    .B1(_04_),
    .B2(in[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a21o_1 _28_ (
    .A1(in[0]),
    .A2(_07_),
    .B1(_09_),
    .X(out[2])
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(in[1]),
    .B(in[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _30_ (
    .A(in[0]),
    .B(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3b_2 _31_ (
    .A(in[3]),
    .B(in[2]),
    .C_N(in[1]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21bai_1 _32_ (
    .A1(_08_),
    .A2(_12_),
    .B1_N(in[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and3_1 _33_ (
    .A(_04_),
    .B(_11_),
    .C(_13_),
    .X(out[3])
  );
endmodule
